### ISSUE TITLE
course and automated reports?

### ISSUE THREAD

**Issue by jhconning** [ilevcovitz/econ_tutoring_sign_in#2]
It would be useful and probably not that hard to have code to: 
1. Automate the generation of the reports.  It would be nice to get scheduled command-line execution of the ipython notebook that's doing the analysis to produce reports. There may already be a built in jupyter/ipython way of doing this... or there is this project: jupyter/ipython  https://github.com/paulgb/runipy.  
   - Runs on schedule say each Thursday morning to updates the HTML output of something like [TutorANalysis](https://github.com/ilevcovitz/econ_tutoring_sign_in/blob/master/analyze/TutorAnalysis.ipynb) 
     - Grabs the latest data exported from the sign-in program from the dropbox folder
     - At top indicates the date the report was generated (and for reference the date of the last entry into the database).
   - generates the report as HTML output of something like [TutorANalysis](https://github.com/ilevcovitz/econ_tutoring_sign_in/blob/master/analyze/TutorAnalysis.ipynb) that anybody with the link could check.
2. Generate course-section reports for individual professors to check.  In principle this should be pretty easy (we can just add a few lines of code to the [TutorANalysis](https://github.com/ilevcovitz/econ_tutoring_sign_in/blob/master/analyze/TutorAnalysis.ipynb) or another notebook to loop through a list of course-sections and generate a report for each written to a file (basically a list of students and when they visited).  We still have to think a bit about how the instructors then retrieve them.  To keep it simple perhaps just have a shared folder where a file called say 10003.csv is available for Econ 100 section 3, etc.  We should think a bit about privacy concerns (maybe a shared password to access the folder that only instructors have).

**Comment by jhconning** [comment]
I got the dropbox folder share.,thanks.   one thought is that the course speciific CSV files ought to include the EMPLID as some instructors might want to merge them in.

**Comment by ilevcovitz** [comment]
Right, I will add those in now.

I also emailed your Hunter account with information about the automated
reports.
